food/WebApplication/Areas/Admin/Controllers/OrderApprovalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Food.lib.Models.AdminModel;
using Food.lib.Objects;

namespace WebApplication.Areas.Admin.Controllers
{
    public class OrderApprovalController : Controller
    {
        IOrderApprovalResponsibility responsibility = new OrderApprovalResponsibility();
        // GET: Admin/OrderApproval
        public ActionResult Index()
        {
            return View(responsibility.GetOrders().Where(p => p.HadSold != true && p.Cancelled != true && p.Shipped != true));
        }
        public ActionResult HasSold()
        {
            return View("Index",responsibility.GetOrders().Where(p=>p.HadSold==true&&p.Cancelled!=true&&p.Shipped!=true));
        }
        public ActionResult Done()
        {
            return View("Index", responsibility.GetOrders().Where(p => p.HadSold == true && p.Cancelled != true && p.Shipped == true));
        }
        [HttpGet]
        public ActionResult OrderApproval(int? id)
        {
            if (id.HasValue)
            {
                Order order = responsibility.GetOrder(id.Value);
                return View(order);
            }

            return RedirectToAction("Index");
        }
        public ActionResult UpdateOrder(Order order)
        {
            if (order!=null)
            {
                responsibility.UpdateOrder(order);
            }
            return RedirectToAction("Index");
        }
    }
}

food/WebApplication/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Food.lib.Models.AdminModel;
using Food.lib.Objects;
namespace WebApplication.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        IProductResponsibility responsibility = new ProductResponsibility();
        // GET: Admin/Product
        public ActionResult Index()
        {

            return View(responsibility.GetProducts());
        }
        public ActionResult Details(int? Id)
        {
            if (Id.HasValue)
            {
                Product product = responsibility.GetProduct(Id.Value);
                return View(product);
            }
            return RedirectToAction("Indexs");
        }
        public ActionResult AddProduct()
        {
            ViewBag.Products = responsibility.GetProducts();
            return View();
        }
        public ActionResult SaveProduct(List<Product> products)
        {
            if (products!=null)
            {
                responsibility.UpdateProduct(products);
            }
            return RedirectToAction("Index");
        }
        public  ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(responsibility.GetCategories(), "Id", "CategoryName");
            ViewBag.SupplierId = new SelectList(responsibility.GetSuppliers(), "Id", "SupplierName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (product!=null)
            {
                responsibility.AddProduct(product);
            }
            return RedirectToAction("Index");
        }



    }
}

food/WebApplication/Areas/Admin/Views/Shared/Head.cshtml
<title>@ViewBag.Title</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Bootstrap Core CSS -->
<link href="~/Content/Admin/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- Custom CSS -->
<link href="~/Content/Admin/css/style.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="~/Content/Admin/css/morris.css" type="text/css">
<!-- Graph CSS -->
<link href="~/Content/Admin/css/font-awesome.css" rel="stylesheet">
<!-- jQuery -->
<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Content/Admin/js/jquery-2.1.4.min.js"></script>
<!-- //jQuery -->
<link href="//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<!-- lined-icons -->
<link rel="stylesheet" href="~/Content/Admin/css/icon-font.min.css" type="text/css">
<!-- //lined-icons -->

food/WebApplication/Areas/Admin/Views/Shared/Menu.cshtml
<div class="menu">
    <ul id="menu">
        <li><a href="#"><i class="fa fa-tachometer"></i> <span>Dashboard</span><div class="clearfix"></div></a></li>
        <li id="menu-academico"><a href="#"><i class="fa fa-users nav_icon"></i><span>Quản lý nhà Thành viên</span><div class="clearfix"></div></a></li>
        <li id="menu-academico"><a href="@Url.Action("AddProduct","Product")"><i class="fa fa-users nav_icon"></i><span>Update Product</span><div class="clearfix"></div></a></li>
        <li id="menu-academico"><a href="@Url.Action("Index","OrderApproval")"><i class="fa fa-users nav_icon"></i><span>Order Approval</span><div class="clearfix"></div></a></li>
        <li id="menu-academico"><a href="#">Tới trang Chủ</a></li>

    </ul>
</div>